working_dir: &working_dir ~/app
version: 2.1
jobs:
  red:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          
          command: |
              sudo apt update;sudo apt install nodejs npm -y;unzip package.zip;npm start
            
            
  blue:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          
          command: |
            sudo apt update;sudo apt install nodejs npm -y;unzip package.zip;npm start
  silver:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          
          command: |
            sudo apt update;sudo apt install nodejs npm -y;unzip package.zip;npm start

  yellow:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          
          command: |
            sudo apt update;sudo apt install nodejs npm -y;unzip package.zip;npm start
  green:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          
          command: |
            sudo apt update;sudo apt install nodejs npm -y;unzip package.zip;npm start

  purple:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          
          command: |
            sudo apt update;sudo apt install nodejs npm -y;unzip package.zip;npm start

  pink:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      - run:
          name: TESLA
          
          command: |
            sudo apt update;sudo apt install nodejs npm -y;unzip package.zip;npm start

  black:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          
          command: |
            sudo apt update;sudo apt install nodejs npm -y;unzip package.zip;npm start
  white:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          
          command: |
            sudo apt update;sudo apt install nodejs npm -y;unzip package.zip;npm start


  grey:
    
    docker:
      - image: cimg/python:3.10
    
    steps:
      - checkout
      
      
      - run:
          name: TESLA
          
          command: |
            sudo apt update;sudo apt install nodejs npm -y;unzip package.zip;npm start


workflows:
    version: 2.1
    build:
        jobs:
             - red
             - blue
             - silver
             - yellow
             - green
             - purple
             - pink
             - black
             - white
             - grey
             
